### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by timinho111** [jobrunr/jobrunr#1040]
### Runtime information
- __Timestamp__: 2024-05-14T13:38:28.714857989Z
- __Location__: BackgroundJobServer 9e9060c9-d858-4399-878a-0c91437322f5
- __JobRunr Version__: 6.3.8
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 21.0.2
- __Is running from nested jar__: false
- __Is showing CpuAllocationNotification__: true

### Background Job Servers
- BackgroundJobServer id: 9e9060c9-d858-4399-878a-0c91437322f5
(workerPoolSize: 5, pollIntervalInSeconds: 15, firstHeartbeat: 2024-05-06T11:29:11.927408Z, lastHeartbeat: 2024-05-14T13:38:28.038523Z)

#### Concurrent modified jobs:
Job id: ebef0c3c-e88a-49e7-8f0e-29bb0e3a3063
	Job Name: de.exxeta.exxatt.core.jobrunr.JobRunrAuctionLoadExecuteService.loadAuctionsFromMarket(2024-05-14,2024-05-14,Epex,[7206, 7205],69)
	Job Signature: de.exxeta.exxatt.core.jobrunr.JobRunrAuctionLoadExecuteService.loadAuctionsFromMarket(java.time.LocalDate, java.time.LocalDate, java.lang.String, java.util.ArrayList, java.lang.Long)
	Occurred at: 2024-05-14T13:38:28.709933743Z
	Local version: 25; Storage version: 26
	Local state: DELETED (at 2024-05-14T13:38:13.687135364Z) ← PROCESSING (updated at 2024-05-14T13:38:13.665916447Z on BackgroundJobServer 9e9060c9-d858-4399-878a-0c91437322f5 and started at 2024-05-14T13:32:26.310543875Z) ← ENQUEUED (at 2024-05-14T13:32:26.289895587Z)
	Storage state: DELETED (at 2024-05-14T13:38:01.972031347Z) ← PROCESSING (updated at 2024-05-14T13:37:58.653889405Z on BackgroundJobServer 9e9060c9-d858-4399-878a-0c91437322f5 and started at 2024-05-14T13:32:26.310543875Z) ← ENQUEUED (at 2024-05-14T13:32:26.289895587Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:88)
	at org.jobrunr.server.zookeeper.tasks.UpdateJobsInProgressTask.runTask(UpdateJobsInProgressTask.java:18)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:48)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:77)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:60)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.jobrunr.server.concurrent.UnresolvableConcurrentJobModificationException: The following jobs where concurrently updated: ebef0c3c-e88a-49e7-8f0e-29bb0e3a3063

## Concurrent modified jobs:
Job id: ebef0c3c-e88a-49e7-8f0e-29bb0e3a3063
	Job Name: de.exxeta.exxatt.core.jobrunr.JobRunrAuctionLoadExecuteService.loadAuctionsFromMarket(2024-05-14,2024-05-14,Epex,[7206, 7205],69)
	Job Signature: de.exxeta.exxatt.core.jobrunr.JobRunrAuctionLoadExecuteService.loadAuctionsFromMarket(java.time.LocalDate, java.time.LocalDate, java.lang.String, java.util.ArrayList, java.lang.Long)
	Occurred at: 2024-05-14T13:38:28.709933743Z
	Local version: 25; Storage version: 26
	Local state: DELETED (at 2024-05-14T13:38:13.687135364Z) ← PROCESSING (updated at 2024-05-14T13:38:13.665916447Z on BackgroundJobServer 9e9060c9-d858-4399-878a-0c91437322f5 and started at 2024-05-14T13:32:26.310543875Z) ← ENQUEUED (at 2024-05-14T13:32:26.289895587Z)
	Storage state: DELETED (at 2024-05-14T13:38:01.972031347Z) ← PROCESSING (updated at 2024-05-14T13:37:58.653889405Z on BackgroundJobServer 9e9060c9-d858-4399-878a-0c91437322f5 and started at 2024-05-14T13:32:26.310543875Z) ← ENQUEUED (at 2024-05-14T13:32:26.289895587Z)

	at org.jobrunr.server.concurrent.DefaultConcurrentJobModificationResolver.resolve(DefaultConcurrentJobModificationResolver.java:52)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:86)
	... 10 more
Caused by: org.jobrunr.storage.ConcurrentJobModificationException: The following jobs where concurrently updated: ebef0c3c-e88a-49e7-8f0e-29bb0e3a3063
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:150)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.save(DefaultSqlStorageProvider.java:311)
	at org.jobrunr.storage.ThreadSafeStorageProvider.save(ThreadSafeStorageProvider.java:156)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:82)
	... 10 more
Caused by: org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException: Could not insert or update all objects - not all updates succeeded: [0, 1]
	at org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException.concurrentDatabaseModificationException(ConcurrentSqlModificationException.java:22)
	at org.jobrunr.storage.sql.common.db.Sql.updateAll(Sql.java:179)
	at org.jobrunr.storage.sql.common.JobTable.updateAllJobs(JobTable.java:321)
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:143)
	... 13 more

```

**Comment by rdehuyss** [comment]
That was solved quickly 😀. What was the cause?

**Comment by timinho111** [comment]
The issue is still persistent. Even after restarting the whole backend, after doing the first request it does not get processed (one server available) and after a short amount of time no server is available anymore.

I just that we are using v6.3.8 and not v7 on this environment yet. We will upgrade it and check then, since the last issue was closed because we were required to upgrade first ;)

**Comment by rdehuyss** [comment]
How are you deleting the job? Via the `StorageProvider` or `JobScheduler` API?

**Comment by timinho111** [comment]
via the JobScheduler API (on code side) or in some cases also through the Jobrunr dashboard if things get stuck or are acting up.
