### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by abdo2011** [jobrunr/jobrunr#137]
### Runtime information
- __Timestamp__: 2021-05-28T04:11:12.042726200Z
- __Location__: BackgroundJobServer 5c13fa61-afcd-4407-8e80-39e0a1d63264
- __JobRunr Version__: Unable to determine version
- __StorageProvider__: org.jobrunr.storage.sql.sqlserver.SQLServerStorageProvider
- __Java Version__: 15.0.2
- __Is running from nested jar__: false

### Background Job Servers
- BackgroundJobServer id: 5c13fa61-afcd-4407-8e80-39e0a1d63264
(workerPoolSize: 64, pollIntervalInSeconds: 15, firstHeartbeat: 2021-05-28T04:07:42.994813900Z, lastHeartbeat: 2021-05-28T04:11:10.890535100Z)

#### Concurrent modified jobs:
Job id: 49d5aaec-b9a6-44f7-8950-a4a0b7a5c5cd
	Local version: 6; Storage version: 6
	Local state: PROCESSING; Storage state: SCHEDULED
	Local last updated: 2021-05-28T04:11:10.266795200Z; Storage last updated: 2021-05-28T04:11:08.864300800Z

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:199)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:147)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:75)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

```

### Runtime information
- __Timestamp__: 2021-05-28T16:59:06.840961500Z
- __Location__: BackgroundJobServer a5245df8-6824-4c8f-b876-753fcda8b16d
- __JobRunr Version__: Unable to determine version
- __StorageProvider__: org.jobrunr.storage.sql.sqlserver.SQLServerStorageProvider
- __Java Version__: 15.0.2
- __Is running from nested jar__: false

### Background Job Servers
No items available

#### Concurrent modified jobs:
Job id: db19b605-a6c3-483d-a7bc-153ead57ead9
	Local version: 3; Storage version: 3
	Local state: SCHEDULED; Storage state: SUCCEEDED
	Local last updated: 2021-05-28T16:59:06.125931Z; Storage last updated: 2021-05-28T16:59:05.990539Z

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:199)
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:183)
	at org.jobrunr.server.JobZooKeeper.checkForOrphanedJobs(JobZooKeeper.java:121)
	at org.jobrunr.server.JobZooKeeper.runMasterTasks(JobZooKeeper.java:96)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:72)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

```

### Runtime information
- __Timestamp__: 2021-05-30T10:21:09.137921900Z
- __Location__: BackgroundJobServer 0a0a6f21-6dc6-4506-9a43-e8de09dffce6
- __JobRunr Version__: Unable to determine version
- __StorageProvider__: org.jobrunr.storage.sql.sqlserver.SQLServerStorageProvider
- __Java Version__: 15.0.2
- __Is running from nested jar__: false

### Background Job Servers
- BackgroundJobServer id: 0a0a6f21-6dc6-4506-9a43-e8de09dffce6
(workerPoolSize: 64, pollIntervalInSeconds: 15, firstHeartbeat: 2021-05-29T17:10:34.298991200Z, lastHeartbeat: 2021-05-30T10:21:09.139920Z)

#### Concurrent modified jobs:
Job id: 36fa96d1-8d30-4537-bf47-0e1923f81bce
	Local version: 2; Storage version: 2
	Local state: PROCESSING; Storage state: SCHEDULED
	Local last updated: 2021-05-30T10:21:09.133918300Z; Storage last updated: 2021-05-30T10:21:09.113653700Z
Job id: 233b70a7-d6d5-4c15-814d-a346d88a919f
	Local version: 10; Storage version: 10
	Local state: PROCESSING; Storage state: FAILED
	Local last updated: 2021-05-30T10:21:09.133918300Z; Storage last updated: 2021-05-30T10:21:09.113653700Z

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:199)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:147)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:75)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

```

### Runtime information
- __Timestamp__: 2021-05-30T11:08:16.765164600Z
- __Location__: BackgroundJobServer 5cfde1e5-c206-4f05-bb89-c08b9c5f8595
- __JobRunr Version__: Unable to determine version
- __StorageProvider__: org.jobrunr.storage.sql.sqlserver.SQLServerStorageProvider
- __Java Version__: 15.0.2
- __Is running from nested jar__: false

### Background Job Servers
- BackgroundJobServer id: 5cfde1e5-c206-4f05-bb89-c08b9c5f8595
(workerPoolSize: 64, pollIntervalInSeconds: 15, firstHeartbeat: 2021-05-30T11:03:13.089382200Z, lastHeartbeat: 2021-05-30T11:08:16.734505600Z)

#### Concurrent modified jobs:
Job id: 632c57ba-95f9-45f2-aaa4-e8e206a7e693
	Local version: 3; Storage version: 3
	Local state: PROCESSING; Storage state: SCHEDULED
	Local last updated: 2021-05-30T11:08:16.761163100Z; Storage last updated: 2021-05-30T11:08:16.750167500Z

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:199)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:147)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:75)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

```

### Runtime information
- __Timestamp__: 2021-05-30T11:42:46.482569300Z
- __Location__: BackgroundJobServer 6fcf0d7b-ad7d-41aa-957d-df9cf1a7e1a9
- __JobRunr Version__: Unable to determine version
- __StorageProvider__: org.jobrunr.storage.sql.sqlserver.SQLServerStorageProvider
- __Java Version__: 15.0.2
- __Is running from nested jar__: false

### Background Job Servers
- BackgroundJobServer id: 6fcf0d7b-ad7d-41aa-957d-df9cf1a7e1a9
(workerPoolSize: 64, pollIntervalInSeconds: 15, firstHeartbeat: 2021-05-30T11:39:51.750120600Z, lastHeartbeat: 2021-05-30T11:42:46.458021300Z)

#### Concurrent modified jobs:
Job id: e71eb668-3274-41aa-b7f7-3ab579bacadf
	Local version: 10; Storage version: 10
	Local state: PROCESSING; Storage state: FAILED
	Local last updated: 2021-05-30T11:42:42.536922Z; Storage last updated: 2021-05-30T11:42:17.598103500Z

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:199)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:147)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:75)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

```

### Runtime information
- __Timestamp__: 2021-05-30T12:40:37.606613800Z
- __Location__: BackgroundJobServer 9ea22ea7-0ac8-4cc8-a6e0-211d69715aae
- __JobRunr Version__: Unable to determine version
- __StorageProvider__: org.jobrunr.storage.sql.sqlserver.SQLServerStorageProvider
- __Java Version__: 15.0.2
- __Is running from nested jar__: false

### Background Job Servers
- BackgroundJobServer id: 9ea22ea7-0ac8-4cc8-a6e0-211d69715aae
(workerPoolSize: 64, pollIntervalInSeconds: 15, firstHeartbeat: 2021-05-30T11:49:43.443135200Z, lastHeartbeat: 2021-05-30T12:40:37.611614Z)

#### Concurrent modified jobs:
Job id: c5fcf62c-f80b-41ad-b166-a79683f0474f
	Local version: 6; Storage version: 6
	Local state: PROCESSING; Storage state: SCHEDULED
	Local last updated: 2021-05-30T12:40:37.573608600Z; Storage last updated: 2021-05-30T12:40:37.145608600Z

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:199)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:147)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:75)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

```

### Runtime information
- __Timestamp__: 2021-05-30T16:20:59.236613600Z
- __Location__: BackgroundJobServer a174175b-d05a-4f8d-a643-7f721bef1be3
- __JobRunr Version__: Unable to determine version
- __StorageProvider__: org.jobrunr.storage.sql.sqlserver.SQLServerStorageProvider
- __Java Version__: 15.0.2
- __Is running from nested jar__: false

### Background Job Servers
No items available

#### Concurrent modified jobs:
Job id: 5ea6a178-39fe-49c8-972e-a24701bff037
	Local version: 2; Storage version: 2
	Local state: SCHEDULED; Storage state: SUCCEEDED
	Local last updated: 2021-05-30T16:20:59.168134400Z; Storage last updated: 2021-05-30T16:20:59.163873800Z

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:199)
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:183)
	at org.jobrunr.server.JobZooKeeper.checkForOrphanedJobs(JobZooKeeper.java:121)
	at org.jobrunr.server.JobZooKeeper.runMasterTasks(JobZooKeeper.java:96)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:72)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

```

**Comment by rdehuyss** [comment]
Hi @abdo2011 , can I ask which JobRunr version you are using?
 I'm still unable to determine the version of JobRunr itself.

Thx!

**Comment by abdo2011** [comment]
Hi @rdehuyss,yes I used 1.3.1  version

**Comment by rdehuyss** [comment]
Could you please update to the latest version? This problem should be solved.

**Comment by abdo2011** [comment]
I migrate to 3.0.1 version but they still have the same issue

**Comment by rdehuyss** [comment]
Can you please elaborate? Did the issue appear again or is the same error message still there? 

There should be a button to dismiss the error and I can't imagine it appearing so fast again, or am I wrong?

**Comment by abdo2011** [comment]
yes, find the below step done :
1- I change the version  jobrunr used by spring boot 
2- I run clean install the project
3- I restart the application.
====>the issue still exist in dashboard

when i click button dismiss the error is disappear even after the restart the application

so that's mean the error fixed ? 
how can i verify that?
Thanks

**Comment by rdehuyss** [comment]
It is expected that the issue is still in the dashboard as it is persisted in the database.

After you upgrade you indeed need to dismiss it and it means that all is well again. So, all is well now.

Please reopen this issue if the dashboard shows the error again.
