### ISSUE TITLE
[BUG] Recent updates to `MethodFinderPredicate` broke functionality

### ISSUE THREAD

**Issue by dontgitit** [jobrunr/jobrunr#1427]
### JobRunr Version

8.2.1

### JDK Version

OpenJDK 21

### Your SQL / NoSQL database

InMemory

### What happened?

The fix for https://github.com/jobrunr/jobrunr/issues/1381 breaks functionality when a `JobRequestHandler` implements run for a specific sub-type of `JobRequest`; the new logic in `MethodFinderPredicate` compares the interface `JobRequest` to the specific job implementation, which always fails.
Maybe a solution is to run both the `equals` and the `isClassAssignable` checks?

### How to reproduce?

My project is in Scala; the code looks something like this:

```scala
trait MyBaseRequestHandler[T <: JobRequest] extends JobRequestHandler[T] {
  final override def run(jobRequest: T): Unit = {
    Await(runFuture(jobRequest))
  }

  protected def runFuture(jobRequest: T): Future[Any]
}

case class ApiJob(
    someId: UUID,
) extends JobRequest{
  override def getJobRequestHandler: Class[ApiJobHandler] = classOf[ApiJobHandler]
}

trait ApiJobHandler extends MyBaseRequestHandler[ApiJob]
```

### Relevant log output

```shell
org.jobrunr.scheduling.exceptions.JobMethodNotFoundException: com.connectstrata.libs.jobs.requests.ApiJobHandler.run(com.connectstrata.libs.jobs.requests.ApiJob)
```

**Comment by dontgitit** [comment]
P.S. this is happening due to type erasure.

Until this is fixed, a temporary workaround is to explicitly redefine `run` so that `getDeclaredMethods` in `ReflectionUtils.findMethod` will find a method with the correct types:
```scala
trait ApiJobHandler extends MyBaseRequestHandler[ApiJob] {
  // explicitly define `run` for `getDeclaredFields`
  override def run(jobRequest: ApiJob): Unit = super.run(jobRequest)
}
```

**Comment by rdehuyss** [comment]
Hi @dontgitit - thanks for notifying us. 

I was really scared to touch that part of the code since I know the impact it could have. 

That being said, we did not have a failing unit test or integration test, so we moved ahead with the change.

People are using JobRunr in ways we can not imagine and in languages we don't officially support...

Would you be able to setup a failing test case for this in our repo? I don't know anything about scala which makes this really difficult.

**Comment by rdehuyss** [comment]
Using `isAssignableFrom` breaks the `JobDetailsTest.testJobDetailsFromInvalidJobRequest()` 😔.

At this moment, I don't know whether we can offer all existing functionality due to type erasure.

**Comment by cmuchinsky** [comment]
> Using `isAssignableFrom` breaks the `JobDetailsTest.testJobDetailsFromInvalidJobRequest()` 😔.
> 
> At this moment, I don't know whether we can offer all existing functionality due to type erasure.

This represents a significant regression for my team as we extensively use inheritance in our job code, is the change that caused this regression worth the cost of breaking functionality for existing users and customers? (Note that we are not using kotlin, our usage is pure java)

**Comment by rdehuyss** [comment]
Hi @cmuchinsky - I know, one of your engineers opened an issue. Is this impacting PRD?

p.s. we have a bank holiday here in Belgium so we're a bit slower to respond.

**Comment by cmuchinsky** [comment]
> Hi [@cmuchinsky](https://github.com/cmuchinsky) - I know, one of your engineers opened an issue. Is this impacting PRD?
> 
> p.s. we have a bank holiday here in Belgium so we're a bit slower to respond.

Hi @rdehuyss, this is not impacting production, we simply can't upgrade past 8.1 as our CICD pipeline is blocked due to `JobMethodNotFoundException` errors during the testing step.

**Comment by rdehuyss** [comment]
Thanks for the swift feedback! We're looking into it and we'll drop you a note as soon as we find a solution.

**Comment by rdehuyss** [comment]
We have a fix for the issue but want to clean up and make sure we don't introduce any other regressions. We'll keep you posted.

**Comment by auloin** [comment]
Thanks for reporting this @dontgitit  and @cmuchinsky. The issue is now fixed and available in 8.2.2 for OSS and 8.2.1 for pro (they should be available shortly via the usual channels).

**Comment by austek** [comment]
Still failing for us at `Arrays.equals(method.getParameterTypes(), parameterTypes)`  in `org.jobrunr.utils.reflection.MethodFinderPredicate#test` 

`parameterTypes = { 'com.collibra.job.samples.SampleProgressTrackedJobRequest'}`

```
SampleProgressTrackedJobRequest extends ProgressTrackedJobRequest
ProgressTrackedJobRequest extends AuthenticatedJobRequest
AuthenticatedJobRequest implements JobRequest
```

`method.getParameterTypes() = {'interface org.jobrunr.jobs.lambdas.JobRequest'}`

**Comment by auloin** [comment]
@austek could you provide enough details so we can reproduce it?

Btw `Arrays.equals(method.getParameterTypes(), parameterTypes)` has been there since 2020.

**Comment by austek** [comment]
> [@austek](https://github.com/austek) could you provide enough details so we can reproduce it?
> 
> Btw `Arrays.equals(method.getParameterTypes(), parameterTypes)` has been there since 2020.

What are you after?

**Comment by rdehuyss** [comment]
Hi @austek !

That's really strange as the previous change causing this bug was ~~almost~~ completely reverted. 

We've also added tests based on your class diagram that failed before and started working again after reverting. Are you sure you're on 8.2.1?

**Comment by dontgitit** [comment]
> Thanks for reporting this [@dontgitit](https://github.com/dontgitit) and [@cmuchinsky](https://github.com/cmuchinsky). The issue is now fixed and available in 8.2.2 for OSS and 8.2.1 for pro (they should be available shortly via the usual channels).

Confirming the issue is fixed for us in 8.2.2! Thanks for the quick turnaround!

**Comment by cmuchinsky** [comment]
> Hi [@austek](https://github.com/austek) !
> 
> That's really strange as the previous change causing this bug was ~almost~ completely reverted.
> 
> We've also added tests based on your class diagram that failed before and started working again after reverting. Are you sure you're on 8.2.1?

@rdehuyss I have managed to reproduce the failure we are seeing locally, see https://github.com/jobrunr/jobrunr/pull/1430 and note the failing `JobDetailsTest`

**Comment by rdehuyss** [comment]
Still not fixed apparently 😔.

**Comment by rdehuyss** [comment]
# Current status
## Real life cluedo

So, the reason this still breaks is because of this addition to [`JobUtils.assertJobExists()`](https://github.com/jobrunr/jobrunr/blob/master/core/src/main/java/org/jobrunr/utils/JobUtils.java#L61-L63) in my fix from yesterday. I added this extra assert to get the test [JobDetailsTest.testJobDetailsFromInvalidJobRequest()](https://github.com/jobrunr/jobrunr/blob/master/core/src/test/java/org/jobrunr/jobs/JobDetailsTest.java#L99-L104) green ✅.

This test was added on request of @jobrunr/collibra as they once had an issue where they copied an implementation of a [`JobRequest`](https://github.com/jobrunr/jobrunr/blob/master/core/src/main/java/org/jobrunr/jobs/lambdas/JobRequest.java) code but forgot to update the method [`getJobRequestHandler()`](https://github.com/jobrunr/jobrunr/blob/master/core/src/main/java/org/jobrunr/jobs/lambdas/JobRequest.java#L15). JobRunr back then did not check whether the link from the `JobRequest` to the `JobRequestHandler` is valid. The addition of an [extra assert check](https://github.com/jobrunr/jobrunr/blob/master/core/src/main/java/org/jobrunr/utils/JobUtils.java#L58-L64) when creating the `JobDetails` solved this and caused an early warning (now a `JobMethodNotFoundException` is thrown when the job is created instead of when JobRunr tries to process the job).


The [PR to fix](https://github.com/jobrunr/jobrunr/pull/1413/files) the [Kotlin related bug](https://github.com/jobrunr/jobrunr/issues/1381) was in fact not related to Kotlin - I can reproduce the [issue also in Java](https://github.com/jobrunr/jobrunr/blob/master/core/src/test/java/org/jobrunr/jobs/JobDetailsTest.java#L124-L128) when one overrides the method `getJobRequestHandler()` using a [default method in an interface](https://github.com/jobrunr/jobrunr/blob/master/core/src/test/java/org/jobrunr/utils/reflection/ReflectionTestClasses.java#L72-L76) which then delegates to another abstract method in the new interface. I originally thought this was related to [Java Bridge methods](https://docs.oracle.com/javase/tutorial/java/generics/bridgeMethods.html) but that's not the case. The problem was that the implementation to find a certain method in [ReflectionUtils](https://github.com/jobrunr/jobrunr/blob/v8.1.0/core/src/main/java/org/jobrunr/utils/reflection/ReflectionUtils.java#L174) was wrong. This was fixed in [PR 1428](https://github.com/jobrunr/jobrunr/blob/master/core/src/main/java/org/jobrunr/utils/reflection/ReflectionUtils.java#L176).

## Options to solve this
Still investigating... I can remove the extra assert in [`JobUtils.assertJobExists()`](https://github.com/jobrunr/jobrunr/blob/master/core/src/main/java/org/jobrunr/utils/JobUtils.java#L61-L63). However, we would not be able to now whether the `JobRequestHandler` matches the `JobRequest` covered in test  [JobDetailsTest.testJobDetailsFromInvalidJobRequest()](https://github.com/jobrunr/jobrunr/blob/master/core/src/test/java/org/jobrunr/jobs/JobDetailsTest.java#L99-L104).

I feel like I'm taking part of a real-life Cluedo...

 ## Update
It was the **ReflectionUtils** guy with the `findMethod` gun 🔫. 
The problem was the way we iterated the class hierarchy tree. This bug was already in there since 2020 🤔.


<img width="800" height="600" alt="Image" src="https://github.com/user-attachments/assets/344156f1-031e-4b6c-a119-819db8baade2" />

**Comment by rdehuyss** [comment]
Reopened due to following bug report in JobRunr Pro by @yigit-karatas.

### JobRunr Version

8.2.2

### JDK Version

Azul Zulu 21.0.5

### Your SQL / NoSQL database

Postgres14

### What happened?

After upgrading from jobrunr version 8.1.0 to 8.2.2 we started seeing `Job method not found` on recurring jobs that are scheduled via lambda. 

Upon investigation we noticed that issue is not on resolving an implementation of the service or finding the method. A condition was added recently to JobUtils as part of [this pr](https://github.com/jobrunr/jobrunr-pro/commit/5052197e5c49280a6e102c4e0404bc1820e4d58e#diff-df3bf6461a2f0ac688d5cf72d7289e0668fd06b861c86f70e37c6b879767f402) which is checking if found method is abstract which seems to be the cause of this issue:
https://github.com/jobrunr/jobrunr-pro/blob/40a050fdf95eafab324648ffe75cd3bb42a35552/core/src/main/java/org/jobrunr/utils/JobUtils.java#L93-L95

### How to reproduce?

Issue can be reproduced by passing job details as lambda where requested service is an interface:
```java
           jobScheduler.createRecurrently(aRecurringJob()
                .withId(recurringJobId)
                .withInterval(Duration.ofSeconds(2))
                .withAmountOfRetries(0)
                .withDetails(MyTestService::performTestTask));
```

Created the following patch to add a unit test which demonstrates the issue :

[issue_on_scheduling_job_with_lambda.patch](https://github.com/user-attachments/files/23611841/issue_on_scheduling_job_with_lambda.patch)

The test case in above patch fails due to `Job method not found`. However, same test passes if the following lines are commented out:
https://github.com/jobrunr/jobrunr-pro/blob/40a050fdf95eafab324648ffe75cd3bb42a35552/core/src/main/java/org/jobrunr/utils/JobUtils.java#L93-L95

### Relevant log output

```shell
2025-11-18T13:38:06.530-05:00 ERROR 1894 --- [roundjob-worker] o.jobrunr.server.BackgroundJobPerformer  : Job(id=019a9842-7fcf-7984-a683-8f28f5786efe, jobName='org.jobrunr.spring.autoconfigure.storage.sql.MyTestService.performTestTask()') processing failed: Job method not found
```
