### ISSUE TITLE
Mongo client 5.0 compatibility

### ISSUE THREAD

**Issue by ChristianMoesl** [jobrunr/jobrunr#948]
We are trying to upgrade our Mongo java client to version 5.0 in our project. But it seems to be incompatible with JobRunr `v6.3.5` right now. Reason is, that version 5 of the mongo client has some [breaking changes](https://www.mongodb.com/docs/drivers/java/sync/current/upgrade/#version-5.0-breaking-changes).

JobRunr fails to run the migrations when executing the `listCollectionNames()` method ([here](https://github.com/jobrunr/jobrunr/blob/master/core/src/main/java/org/jobrunr/storage/nosql/mongo/migrations/MongoMigration.java#L30)). The documentation about this breaking change suggests, that JobRunr needs to be compiled against this new Mongo driver version to fix that and it doesn't require a code change:
<img width="758" alt="image" src="https://github.com/jobrunr/jobrunr/assets/17096190/80157d80-cdc9-4e9b-beba-2f7997983a36">

Could you update the mongo driver version in your platform package to version `5.0.0`? 

Thanks!

**Comment by ChristianMoesl** [comment]
Sorry, I accidentally closed this issue.

**Comment by rdehuyss** [comment]
Will do, but only in v7 branch.

**Comment by rdehuyss** [comment]
Solved in branch v7.

**Comment by adini85** [comment]
@rdehuyss Seems still an issue on v7.1.1: it happens when MongoDB migration is applied (to create JobRunr collection).

**Comment by kschlesselmann** [comment]
@rdehuyss I can confirm that this seems to be still an issue. Please re-open this ticket.

**Comment by rdehuyss** [comment]
We have automated tests that confirm this is not the case. Please create an repo that reproduces it - then we will have a look.
